import type { CompanyProfile, ItemState, Plan, Phase } from '../types';
import {
  CATEGORY_LABELS,
  COST_LABELS,
  EFFORT_LABELS,
  PHASE_LABELS,
  PHASE_ORDER,
} from '../types';

const STATUS_MARKS: Record<string, string> = {
  done: '[x]',
  'in-progress': '[~]',
  todo: '[ ]',
  na: '[–]',
};

/** Render the plan as a Markdown document suitable for sharing or archiving. */
export function planToMarkdown(
  profile: CompanyProfile,
  plan: Plan,
  items: Record<string, ItemState>,
): string {
  const lines: string[] = [];
  const name = profile.companyName.trim() || 'Your startup';

  lines.push(`# Security Plan: ${name}`);
  lines.push('');
  lines.push(`Generated by Groundwork on ${new Date().toISOString().slice(0, 10)}.`);
  if (profile.description.trim()) {
    lines.push('');
    lines.push(`> ${profile.description.trim()}`);
  }
  lines.push('');
  lines.push('Legend: `[x]` done · `[~]` in progress · `[ ]` to do · `[–]` not applicable');

  for (const phase of PHASE_ORDER as Phase[]) {
    const phaseItems = plan.items.filter((i) => i.phase === phase);
    if (phaseItems.length === 0) continue;
    lines.push('');
    lines.push(`## ${PHASE_LABELS[phase]}`);
    for (const item of phaseItems) {
      const state = items[item.control.id];
      const mark = STATUS_MARKS[state?.status ?? 'todo'];
      lines.push('');
      lines.push(
        `### ${mark} ${item.control.title}`,
      );
      lines.push('');
      lines.push(
        `*${CATEGORY_LABELS[item.control.category]} · Effort: ${EFFORT_LABELS[item.control.effort]} · Cost: ${COST_LABELS[item.control.cost]}*`,
      );
      lines.push('');
      lines.push(`**Why:** ${item.control.why}`);
      lines.push('');
      lines.push(`**Why it's in your plan:** ${item.reasons.join(' ')}`);
      lines.push('');
      lines.push('**How:**');
      for (const step of item.control.how) {
        lines.push(`- ${step}`);
      }
      if (item.control.tools?.length) {
        lines.push('');
        lines.push(`**Tools to consider:** ${item.control.tools.join(', ')}`);
      }
      if (item.control.frameworks?.length) {
        lines.push('');
        lines.push(`**Framework mapping:** ${item.control.frameworks.join(' · ')}`);
      }
      if (state?.note.trim()) {
        lines.push('');
        lines.push(`**Notes:** ${state.note.trim()}`);
      }
    }
  }

  lines.push('');
  return lines.join('\n');
}
