import { chromium } from 'playwright-core';
const S='/tmp/claude-0/-home-user-Mneme-Labs/c1337d8e-b042-54bf-abb0-15c696a6be0e/scratchpad/';
const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium' });
const p = await b.newPage({ viewport:{width:1200,height:1000}, deviceScaleFactor:1.5 });
const errs=[]; p.on('console', m=>{ if(m.type()==='error') errs.push(m.text()); });
p.on('pageerror', e=>errs.push('PAGEERROR: '+e.message));
await p.goto('http://localhost:4182/',{waitUntil:'networkidle'}); await p.waitForTimeout(500);
await p.screenshot({path:S+'v3-landing.png'});
await p.locator('text=Build my security plan').click();
await p.waitForSelector('.wizard');
await p.locator('input[type=text]').fill('Nimbus');
await p.locator('textarea').fill('A SaaS platform for engineering teams.');
await p.locator('button:has-text("2–10 people")').click();
await p.locator('button:has-text("Launched")').click();
await p.waitForTimeout(300); await p.screenshot({path:S+'v3-wizard.png'});
await p.locator('button:has-text("Continue")').click();
await p.locator('button:has-text("Web app / SaaS")').click();
await p.locator('button:has-text("Personal data")').click();
await p.locator('button:has-text("Continue")').click();
await p.locator('button:has-text("Azure")').click();
await p.locator('.choice-grid button:has-text("GitHub")').click();
await p.locator('button:has-text("Continue")').click();
await p.locator('button:has-text("Fully remote")').click();
await p.locator('button:has-text("Continue")').click();
await p.locator('button:has-text("Businesses (B2B)")').click();
await p.locator('.choice-grid button:has-text("SOC 2")').click();
await p.locator('button:has-text("Continue")').click();
await p.locator('button:has-text("MFA on important accounts")').click();
await p.locator('button:has-text("Generate my plan")').click();
await p.waitForSelector('.dashboard'); await p.waitForTimeout(700);
await p.screenshot({path:S+'v3-dashboard.png'});
const itemCount = await p.locator('.item-card').count();
await p.locator('.item-title').first().click(); await p.waitForTimeout(400);
await p.screenshot({path:S+'v3-item.png'});
await p.locator('.status-btn').first().click(); await p.waitForTimeout(400);
const before = await p.locator('.ring-text').textContent();
await p.reload({waitUntil:'networkidle'}); await p.waitForTimeout(800);
const after = await p.locator('.ring-text').textContent();
await p.locator('button:has-text("Security report")').click();
await p.waitForSelector('.report'); await p.waitForTimeout(500);
await p.screenshot({path:S+'v3-report.png'});
await b.close();
console.log(JSON.stringify({itemCount, ringBefore:before, ringAfter:after, persisted: before===after, errors:errs}));
